### PR TITLE
Fixes #14. Add .Elapsed to Operation.

### LINKED ISSUE #14: Feature Request: Warn if exceeds
I started porting all of my timing code away from `SerilogMetrics` and ran into one case that I find quite useful. The other library had a notion of wrapping a block of code and logging a warning if it exceeded a certain time threshold. It would be great to have this feature.

Alternatively, I looked for an `.ElapsedTime` property on the `Operation` class but didn't see one. Would be nice to have that hydrated upon calling `.Complete()`.

### PR DESCRIPTION
**Pull request by davidpeden3**

### CODE REVIEW

**Comment by davidpeden3** [comment]
@pardahlman Yeah, I noticed it after making the commit and fixed it in https://github.com/nblumhardt/serilog-timings/pull/19/commits/18839295a58f0209a1eb68b91769443f9369be9f.

**Comment by nblumhardt** [comment]
Looks good! Thanks for the PR, David.

Since any changes here will flow into #20, I'll add comments over there (we might just merge the one?). It'll be hard to make changes in this PR that flow down to the other one, otherwise.

**Comment by davidpeden3** [comment]
Cool, yeah if you merge this one in, I'll sync the other ones.

**Comment by nblumhardt** [comment]
Better late than never, from me! :-)

**Pull request merged**
