### PR TITLE
Core3

### PR DESCRIPTION
**Pull request by Jens-H-Eriksen**
I've updated the solution to .Net Core 3.0, Net standard 2.0 and .Net Framework 4.72 
This was done due to problems using the package in a .Net Core 3.1 project using Serilog 2.9

### CODE REVIEW

**Comment by Jens-H-Eriksen** [comment]
There seems to be a problem with the buildscript.

**Comment by Jens-H-Eriksen** [comment]
Fixed build script... please review and merge

**Comment by Jens-H-Eriksen** [comment]
Hmmm.... I still have a problem: 

this is logging
` using (Operation.Time("FindShelfForMaterial: {Item} {outcome} in {elapsed:0.0} ms ", component.Item))`
this is not:
` using (Operation.Time("FindShelfForMaterial: {Item} ", component.Item))`

cannot figure out why?!

**Comment by nblumhardt** [comment]
Hi! Thanks for the PR 👍 

Unfortunately, you've based this on `master`, while `dev` has already moved ahead and now supports `netstandard2.0`/CSPROJ etc.

I'll make a release by merging `dev` to `master`; if the new package doesn't help, please feel free to send a PR.

Closing, but thanks for your efforts!

**Comment by Jens-H-Eriksen** [comment]
I did try to upgrade to ver 2.3 but still get the strange behavior mentioned above. 
Rebased my changes onto dev and tried that out too... same problem

**Pull request closed without merging**
